# Generated by Django 5.0 on 2024-03-07 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_profile_first_name_alter_profile_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='social_media_link',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
