# Generated by Django 5.0.2 on 2024-02-13 07:57

import django.core.validators
import django.db.models.deletion
import video.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrimeVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='crime_videos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'mp4', 'mkv', 'webm']), video.models.validate_video_size])),
                ('description', models.TextField(blank=True, null=True)),
                ('title', models.CharField(max_length=300)),
                ('view_count', models.IntegerField(default=0)),
                ('views_by_devices', models.JSONField(default=list)),
                ('is_solved', models.BooleanField(default=False)),
                ('is_onboard', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(max_length=400)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.crimevideos')),
            ],
        ),
        migrations.CreateModel(
            name='EntertainmentVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='entertainment_videos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'mp4', 'mkv', 'webm']), video.models.validate_video_size])),
                ('description', models.TextField(blank=True, null=True)),
                ('title', models.CharField(max_length=300)),
                ('view_count', models.IntegerField(default=0)),
                ('views_by_devices', models.JSONField(default=list)),
                ('is_solved', models.BooleanField(default=False)),
                ('is_onboard', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EntertainmentComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(max_length=400)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.entertainmentvideos')),
            ],
        ),
    ]
