# Generated by Django 4.2.6 on 2024-02-14 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_alter_crimevideos_is_onboard_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crimevideos',
            name='video',
            field=models.FileField(upload_to='crime_videos'),
        ),
    ]
